import config from '../../public/config.json'
const path = {
	//baseUrl : "http://124.222.138.89:5000",
	// baseUrl : "http://10.6.12.158:5000",
	baseUrl: config.baseURL,
	login : "/user/login",
	register: "/user/register",
	uploadImg: "/user/clockIn",
	uploadFaceImg: "/HR/createUserFace",
	searchAllDepartment:'/user/queryAllDepartments',
	getDepartment:'/user/userInDepartment',
	userApplyDepartment:"/user/userApplyDepartment",
	createDepartment: "/HR/createDepartment",
	queryDepartmentDetail: "/user/queryDepartmentDetail",
	usersInDepartment: "/HR/usersInDepartment",
	applyDeleteDepartment: "/HR/applyDeleteDepartment",
	grantUserHR: "/HR/grantUserHR",
	queryMyApplications: "/user/queryMyApplications",
	processMyApplications:"/user/processMyApplications",
	userClockData: "/user/userClockData",
	updateDepartConfig : "/HR/updateDepartConfig",
	queryAllUsers:"/HR/queryAllUsers",
	inviteUserJoinDepart:"/HR/inviteUserJoinDepart",
	userBaseData: "/user/userBaseData",
	dismissUserInDepart:"/HR/dismissUserInDepart",
	passwordPolish:"/user/updatePassword",
	getUserInfo:"/user/userBaseData",
	infoPolish:"/user/userUpdate",
	avatarUpload:'/user/uploadHeadImg',
	getOnesCompany:'/user/userInDepartment',
	getOnesEmployee:'/HR/usersInDepartment',
	makeUpClock:"/user/makeUpClock",
	userClockInfo: "/user/userClockInfo",
	userLeave: "/user/userLeave",
	workOvertime :"/user/workOverTime",
	usersInDepartments:"/HR/usersInDepartments",
	allDepartmentsClockData:"/HR/allDepartmentsClockData",
	firstPage:"/user/firstPage",
	clockOut :"/user/clockOut",
	userClockDayData:"/user/userClockDayData",
	handClockOut: "/user/handClockOut",
	handClockIn: "/user/handClockIn",
	userTodoLists:"/user/userTodoLists",
	updateTodoLists:"/user/updateTodoLists",
	addTodoLists : "/user/addTodoLists",
	exportExcel:"/HR/exportExcel",
	isUidInDepartment:"/user/isUidInDepartment"
}
export default path;